services:
  - docker
jobs:
  include:
    - stage: build image for sandbox
      if: branch = "docker_build"
      script:
        - echo "$DOCKER_SECRET" | docker login -u "$DOCKER_USER" docker.io --password-stdin
        - docker build -t build-image .
#        - docker exec -it build-image bash -c './artisan dusk'
        - docker tag build-image:latest "$DOCKER_USER"/srr:mod-development
        - docker logout
        - echo "$DOCKER_SECRET" | docker login -u "$DOCKER_USER" docker.io --password-stdin
        - docker push "$DOCKER_USER"/srr:mod-development
#      deploy:
#        - provider: cloudfoundry
#          api: https://api.cloud.service.gov.uk
#          username: "$CF_USERNAME"
#          password:
#            secure: "$CF_PASSWORD"
#          organization: mod-request-a-historic-service-record
#          space: development
##          on:
##            repo: servicerecords/mod-ssr
##            branch: development
#          skip_cleanup: 'true'
#          manifest: manifest-sandbox.yml


notifications:
  email:
    recipients:
      #      - amanda.moran637@mod.gov.uk
      #      - liam.cusack582@mod.gov.uk
      - toby@codesure.co.uk
    on_success: always
    on_failure: always
#deploy:
#  - provider: cloudfoundry
#    api: https://api.cloud.service.gov.uk
#    username: "$CF_USERNAME"
#    password:
#      secure: "$CF_PASSWORD"
#    organization: mod-request-a-historic-service-record
#    space: development
#    on:
#      repo: servicerecords/mod-ssr
#    skip_cleanup: 'true'
#    manifest: manifest-sandbox.yml
#  - provider: cloudfoundry
#    api: https://api.cloud.service.gov.uk
#    username: "$CF_USERNAME"
#    password:
#      secure: "$CF_PASSWORD"
#    organization: mod-request-a-historic-service-record
#    space: development
#    on:
#      repo: servicerecords/mod-ssr
#    skip_cleanup: 'true'
#    manifest: manifest-qa.yml
