#language: php
services:
- docker
jobs:
  include:
  - stage: building docker image
    script:
    - echo "$GITHUB_SECRET" | docker login https://docker.pkg.github.com -u "$GITHUB_USER"
      --password-stdin
    - docker build -t travis-ci-build-stage .
    - docker images
    - docker tag travis-ci-build-stage:latest docker.pkg.github.com/servicerecords/mod-ssr/mod-srr:0."$TRAVIS_BUILD_NUMBER".3
    - docker push docker.pkg.github.com/servicerecords/mod-ssr/mod-srr:0."$TRAVIS_BUILD_NUMBER".3
notifications:
  email:
    recipients:
    - amanda.moran637@mod.gov.uk
    - liam.cusack582@mod.gov.uk
    - toby@codesure.co.uk
    on_success: always
    on_failure: always
#deploy:
#  - provider: cloudfoundry
#    api: https://api.cloud.service.gov.uk
#    username: "$CF_USERNAME"
#    password:
#      secure: "$CF_PASSWORD"
#    organization: mod-request-a-historic-service-record
#    space: development
#    on:
#      repo: servicerecords/mod-ssr
#    skip_cleanup: 'true'
#    manifest: manifest-sandbox.yml
#  - provider: cloudfoundry
#    api: https://api.cloud.service.gov.uk
#    username: "$CF_USERNAME"
#    password:
#      secure: "$CF_PASSWORD"
#    organization: mod-request-a-historic-service-record
#    space: development
#    on:
#      repo: servicerecords/mod-ssr
#    skip_cleanup: 'true'
#    manifest: manifest-qa.yml
