env:
#  global:
#  - CF_API=api.cloud.service.gov.uk
#  - CF_ORGANIZATION=mod-request-a-historic-service-record
#  - CF_USERNAME=toby@codesure.co.uk
#  - secure: Rlal6uRpsfYlp0xLuIpd4w5SGdiaUG5nQEW4AJf9LBb+Hnmkryp9iJ4t4g16/kbEmg54cv3b930ulRoLFlLx0ZggsE0kaMi8z01e4xHIZeGP3onSUlidnlFysgmpg/+6wOlIyfDKvfWIq8mZNCPdGGVc6k9D6bkDTS3E/B+ZZxAq8JkDnzQFpUwAnRzEsO/tKZ41J78Wc2SSHE5qCsQ8BF4nnGbBG2YtcaBZTJDt9noWqYuHpBvMZxmJNsgPphMS6n9sUrGUg8C/A3dOBR/J/j/yJz5n0uNlWOWyf/qzDPT+TUpW1CJP+6v4QVdwMdR8AyVWuEeRZVo+eJkxfL2bvRdu3NIzUGfGgfel70HZFrUjsONliy37L5beBhMuXI1hHyxU6g3NXwkA1zE4I03g+rudLGdrPFs1Vg2XL4kJsTsqvS5ylUEFcHt6q4KvYF5W73h6iRheGROL/HUYoTRNncnrsCK1vNkCCNClzzfFd3v5ck3RseLW3kTi1rZV1zN6UErAEdpyQctxb/hgRTootygqJlICy6g09YbNXj8pGqsiJxtFHaHI2tiEaVviqsf63aEGA7J1RyG9+p67sadDdymCooeHzD3GFndOfgKqOU8coXTLqcrDYe7T7+5hDP/Vho7jQORshSYvj5LtgNkPblsvQl2LTKCoA8dTAxLSlGE=
addons:

  chrome: stable

install:
  - cp .env.testing .env
  - travis_retry composer install --no-interaction --prefer-dist
  - php artisan key:generate
  - php artisan dusk:chrome-driver

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve --no-reload &

script:
  - php artisan dusk

jobs:
  include:
    - stage: Build Docker Image for branch
      if: branch IN ("sandbox", "qa", "master", "phase2")
      script:
        - env | while IFS= read -r line; do value=${line#*=} name=${line%%=*} echo "V $value" echo "N $name" done
        - chmod 755 ci/deploy_to_cf.sh

notifications:
  email:
    recipients:
      - toby@codesure.co.uk

deploy:
  provider: cloudfoundry
  api: https://api.cloud.service.gov.uk
  username: toby@codesure.co.uk
  password:
    secure: Fuifj7RCGl6/SITU2Y0G9f9BTohemK9HYYKayI+pDvYF5ICioganOAP2zX8Anc0GPtEsikO+aaJb0dbqhvh+ndq2LqmrVl2pH4VdfDQGyxkq8xisTeWphR7lZ4H/cbITJ47RdJJBV/O0KWNhL8EOgPED1jMIlreWqXZxR4LLc1mHzvWbl82w7oEldk6ciKXiyMgrisPiX3OouAHrv1RKnDaorbU+rGwfB6WmhLF5qWbZz9dOhQ1XIeVkWmpIV0IDL8oAAvGE6OAYc4IPj+FSbnyBPBVs2qaTO0NB1MMk8PkmZWzQPPcyU/JUCg9Y0UkQF1+D05hxeH13HuuAA/tLMF3aAdA1klvZMjUCAAMjD1+nDYgZUyhEJ/zVABEB3WArUbfRC0WZtPeCSse7su27OXZ1L+vSQUWA/g6QvLii5tGVgdHlbzsj9KlQF9lvO9SJRmaopDwtT38NdIhNoNp2JxVqKZv4i7lW3/g1/6iE2ONLaSpDM/zUXD5ld7mQWBOahT8T5+QJh3wAtgRwvWr5aTswz1CF5r35Y/daoTcWWSN6PA+kD1uchb4hA+giC1dsREJBeDoADrC63m+ern2O1G1BSIgBNZYbyziNwf6sgzfBOnEYdP7CwTayTY2i2N523+uYHqJPFfdftfsEeNt/xsxiwGcKM9R2aPtF7mzDbcs=
  organization: mod-request-a-historic-service-record
  space: development
  on:
    repo: servicerecords/adpmr
    branch: phase2
  skip_cleanup: 'true'
