services:
  - docker
jobs:
  include:
    - stage: build image for sandbox
      if: branch = "docker_build"
      script:
        - echo "$DOCKER_SECRET" | docker login -u "$DOCKER_USER" docker.io --password-stdin
        - docker build -t build-image .
        - docker exec -it build-image bash -c './artisan dusk'
        - docker tag build-image:latest "$DOCKER_ORGANISATION"/srrdigital:sandbox
        - docker logout
        - echo "$DOCKER_SECRET" | docker login -u "$DOCKER_USER" docker.io --password-stdin
        - docker push "$DOCKER_ORGANISATION"/srrdigital:sandbox

      deploy:
        - provider: script
          skip_cleanup: true
          script: env CF_SPACE=development CF_APP_NAME=docker_deploy CF_MANIFEST=manifest-test.yml

