services:
  - docker
jobs:
  include:
    - stage: building docker image
      script:
        - echo "$DOCKER_SECRET" | docker login -u "$DOCKER_USER" --password-stdin
        - docker build -t build-image .
        - docker images
        - docker tag build-image:latest codesuretoby/srr:mod-sandbox-"$TRAVIS_BUILD_NUMBER"
        - docker push codesuretoby/srr:mod-sandbox-"$TRAVIS_BUILD_NUMBER"
        - docker tag build-image:latest codesuretoby/srr:mod-qa-"$TRAVIS_BUILD_NUMBER"
        - docker push codesuretoby/srr:mod-qa-"$TRAVIS_BUILD_NUMBER"
        - docker tag build-image:latest codesuretoby/srr:mod-production-"$TRAVIS_BUILD_NUMBER"
        - docker push codesuretoby/srr:mod-production-"$TRAVIS_BUILD_NUMBER"
        - CF_DOCKER_PASSWORD="$CF_PASWORD" cf push Green -n docker_app-green -k 2G --docker-image codesuretoby/srr:mod-sandbox-"$TRAVIS_BUILD_NUMBER" --docker-username "$CF_USERNAME"


notifications:
  email:
    recipients:
#      - amanda.moran637@mod.gov.uk
#      - liam.cusack582@mod.gov.uk
      - toby@codesure.co.uk
    on_success: always
    on_failure: always
#deploy:
#  - provider: cloudfoundry
#    api: https://api.cloud.service.gov.uk
#    username: "$CF_USERNAME"
#    password:
#      secure: "$CF_PASSWORD"
#    organization: mod-request-a-historic-service-record
#    space: development
#    on:
#      repo: servicerecords/mod-ssr
#    skip_cleanup: 'true'
#    manifest: manifest-sandbox.yml
#  - provider: cloudfoundry
#    api: https://api.cloud.service.gov.uk
#    username: "$CF_USERNAME"
#    password:
#      secure: "$CF_PASSWORD"
#    organization: mod-request-a-historic-service-record
#    space: development
#    on:
#      repo: servicerecords/mod-ssr
#    skip_cleanup: 'true'
#    manifest: manifest-qa.yml
