language:
  php

php:
  - '8.0'

notifications:
  email:
    recipients:
      - toby@codesure.co.uk

before_script: composer require phpunit/phpunit

deploy:
  provider: cloudfoundry
  deployment_strategy: rolling
  api: ${CF_API}
  username: ${CF_USERNAME}
  password:
    secure: "a4ycLKYPCIZUFmiM5Cdqn0H6sR1533DKToekvXtkxYUXq4UXU2r18e42ttxXfqsM4pm7NK0LohtwCJql35B/T8oxY7gXK9QFYCWweQMOnMQc828xXxmZ6wDoWv035JV2GF/G6ADuJqLvWJVaBYneMg6jbPuvWw0cMoeN69emgOHCCd1WC9X33lHGq25rz8QqpCevmo3J5ySGgB+xzqLDljSU0x4cdxD+wK/lOfhBRY6qJZCl7Ptr4OnJCzCmFHFNIy6eQEzobBpeLJYQSfUgaPg1/IxKUBGexDEKkc/IY9vN1fsbK7/zwFlUPCZx9uzuDSelVZr+A0jUbdlnK9h5cmM+8Gy1qvaDEQiQeMLk8CbTUlj0ZH7NfJ7u9Jkb9yS3MGkNlaNuR/L/DoF1rVzvjpwOW1R65Smu1fmtmv95m6v73aCmpglCNo5nlfLb/zqvebteVj2CRNF3PTxK5Jv+d3M0qr9uqhezRnCv/YQXipgv6926o9CvEVLw0b6oUUSF7goCum0/TCweYIAN945dNO9Ypes9zlmMVGORZNMQXLxw44iLTOD8AUpYPqJxznOPlspRnQSi5xBl0nUo11ecpe4V/pnUm8MRO11kuD3EUg0+oInJDg+eZSjL/OSDeg2V9lljDg+ACh3ZqboaTyuLIqDD3FFBZJll52L5/Mbz99A="
  organization: ${CF_ORGANISATION}
  space: ${CF_SPACE}
  on:
    repo: ${CF_REPO}
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(sandbox|qa|master)$
  skip_cleanup: 'true'
